/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Abcd
 */
public class Dashboard2 extends javax.swing.JFrame {

	/**
	 * Creates new form Dashboard
	 */
	public Dashboard2() {

		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		DashboardPanel = new JPanel();
		SlidingMenu = new javax.swing.JPanel();
		HideMenu = new javax.swing.JLabel();
		StockSales = new javax.swing.JLabel();
		Inventory = new javax.swing.JLabel();
		StockIn = new javax.swing.JLabel();
		ActivityLogs = new javax.swing.JLabel();
		ClientRecords = new javax.swing.JLabel();
		LogOut = new javax.swing.JLabel();
		BitMonke = new javax.swing.JLabel();
		OpenMenu = new javax.swing.JLabel();
		OpenMenu.setForeground(new Color(43, 52, 59));
		Bar = new javax.swing.JLabel();
		layeredPane = new javax.swing.JLayeredPane();
		InventoryPanel = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		ActivityLogsPanel = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		ClientRecordsPanel = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		StockInPanel = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		SalesReportPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		DashboardPanel.setBackground(new java.awt.Color(204, 204, 204));

		SlidingMenu.setBackground(new Color(43, 52, 59));
		SlidingMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(51, 51, 51)));

		HideMenu.setBackground(new java.awt.Color(153, 153, 153));
		HideMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		HideMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/hide_1.png"))); // NOI18N
		HideMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		HideMenu.setOpaque(true);
		HideMenu.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				HideMenuMouseReleased(evt);
			}
		});

		StockSales.setBackground(new java.awt.Color(153, 153, 153));
		StockSales.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
		StockSales.setForeground(new java.awt.Color(0, 0, 0));
		StockSales.setText("     Sales Report");
		StockSales.setOpaque(true);
		StockSales.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				StockSalesMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				StockSalesMouseExited(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				StockSalesMouseReleased(evt);
			}
		});

		Inventory.setBackground(new java.awt.Color(153, 153, 153));
		Inventory.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
		Inventory.setForeground(new java.awt.Color(0, 0, 0));
		Inventory.setText("     Inventory");
		Inventory.setOpaque(true);
		Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				InventoryMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				InventoryMouseExited(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				InventoryMouseReleased(evt);
			}
		});

		StockIn.setBackground(new java.awt.Color(153, 153, 153));
		StockIn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
		StockIn.setForeground(new java.awt.Color(0, 0, 0));
		StockIn.setText("     Stock In");
		StockIn.setOpaque(true);
		StockIn.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				StockInMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				StockInMouseExited(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				StockInMouseReleased(evt);
			}
		});

		ActivityLogs.setBackground(new java.awt.Color(153, 153, 153));
		ActivityLogs.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
		ActivityLogs.setForeground(new java.awt.Color(0, 0, 0));
		ActivityLogs.setText("     Activity Logs");
		ActivityLogs.setOpaque(true);
		ActivityLogs.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				ActivityLogsMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				ActivityLogsMouseExited(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				ActivityLogsMouseReleased(evt);
			}
		});

		ClientRecords.setBackground(new java.awt.Color(153, 153, 153));
		ClientRecords.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
		ClientRecords.setForeground(new java.awt.Color(0, 0, 0));
		ClientRecords.setText("     Client Records");
		ClientRecords.setOpaque(true);
		ClientRecords.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				ClientRecordsMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				ClientRecordsMouseExited(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				ClientRecordsMouseReleased(evt);
			}
		});

		LogOut.setBackground(new java.awt.Color(153, 153, 153));
		LogOut.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
		LogOut.setForeground(new java.awt.Color(0, 0, 0));
		LogOut.setText("     Log out");
		LogOut.setOpaque(true);
		LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				LogOutMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				LogOutMouseExited(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				LogOutMouseReleased(evt);
			}
		});

		BitMonke.setBackground(new java.awt.Color(153, 153, 153));
		BitMonke.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
		BitMonke.setForeground(new java.awt.Color(102, 102, 102));
		BitMonke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		BitMonke.setText("BitMonke");
		BitMonke.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

		javax.swing.GroupLayout SlidingMenuLayout = new javax.swing.GroupLayout(SlidingMenu);
		SlidingMenu.setLayout(SlidingMenuLayout);
		SlidingMenuLayout.setHorizontalGroup(SlidingMenuLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(HideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGroup(SlidingMenuLayout.createSequentialGroup().addGap(26, 26, 26).addComponent(BitMonke,
						javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addComponent(StockSales, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(StockIn, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(ActivityLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(ClientRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
						javax.swing.GroupLayout.PREFERRED_SIZE));
		SlidingMenuLayout
				.setVerticalGroup(
						SlidingMenuLayout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(SlidingMenuLayout.createSequentialGroup()
										.addComponent(HideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(6, 6, 6)
										.addComponent(BitMonke, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(StockSales, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(6, 6, 6)
										.addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(6, 6, 6)
										.addComponent(StockIn, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(6, 6, 6)
										.addComponent(ActivityLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(6, 6, 6)
										.addComponent(ClientRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(6, 6, 6)
										.addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		OpenMenu.setBackground(new Color(43, 52, 59));
		OpenMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		OpenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/menu (1).png"))); // NOI18N
		OpenMenu.setOpaque(true);
		OpenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				OpenMenuMouseReleased(evt);
			}
		});

		Bar.setBackground(new Color(43, 52, 59));
		Bar.setOpaque(true);

		layeredPane.setLayout(new java.awt.CardLayout());

		InventoryPanel.setBackground(new java.awt.Color(0, 51, 153));

		jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(0, 0, 0));
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("Inventory");

		javax.swing.GroupLayout InventoryPanelLayout = new javax.swing.GroupLayout(InventoryPanel);
		InventoryPanel.setLayout(InventoryPanelLayout);
		InventoryPanelLayout.setHorizontalGroup(InventoryPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(InventoryPanelLayout
						.createSequentialGroup().addGap(400, 400, 400).addComponent(jLabel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		InventoryPanelLayout
				.setVerticalGroup(
						InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(InventoryPanelLayout.createSequentialGroup().addGap(118, 118, 118)
										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(401, Short.MAX_VALUE)));

		layeredPane.add(InventoryPanel, "card3");

		ActivityLogsPanel.setBackground(new java.awt.Color(153, 0, 204));

		jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(0, 0, 0));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("ActivityLogs");

		javax.swing.GroupLayout ActivityLogsPanelLayout = new javax.swing.GroupLayout(ActivityLogsPanel);
		ActivityLogsPanel.setLayout(ActivityLogsPanelLayout);
		ActivityLogsPanelLayout.setHorizontalGroup(
				ActivityLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(ActivityLogsPanelLayout.createSequentialGroup().addGap(400, 400, 400)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		ActivityLogsPanelLayout
				.setVerticalGroup(
						ActivityLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(ActivityLogsPanelLayout.createSequentialGroup().addGap(118, 118, 118)
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(401, Short.MAX_VALUE)));

		layeredPane.add(ActivityLogsPanel, "card4");

		ClientRecordsPanel.setBackground(new java.awt.Color(153, 0, 0));

		jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(0, 0, 0));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("Client Records");

		javax.swing.GroupLayout ClientRecordsPanelLayout = new javax.swing.GroupLayout(ClientRecordsPanel);
		ClientRecordsPanel.setLayout(ClientRecordsPanelLayout);
		ClientRecordsPanelLayout.setHorizontalGroup(
				ClientRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(ClientRecordsPanelLayout.createSequentialGroup().addGap(400, 400, 400)
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		ClientRecordsPanelLayout
				.setVerticalGroup(
						ClientRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(ClientRecordsPanelLayout.createSequentialGroup().addGap(118, 118, 118)
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(401, Short.MAX_VALUE)));

		layeredPane.add(ClientRecordsPanel, "card5");

		StockInPanel.setBackground(new java.awt.Color(0, 153, 0));

		jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(0, 0, 0));
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel5.setText("Stock In");

		javax.swing.GroupLayout StockInPanelLayout = new javax.swing.GroupLayout(StockInPanel);
		StockInPanel.setLayout(StockInPanelLayout);
		StockInPanelLayout
				.setHorizontalGroup(StockInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(StockInPanelLayout.createSequentialGroup().addGap(400, 400, 400)
								.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		StockInPanelLayout
				.setVerticalGroup(
						StockInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(StockInPanelLayout.createSequentialGroup().addGap(118, 118, 118)
										.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(401, Short.MAX_VALUE)));

		layeredPane.add(StockInPanel, "card6");

		SalesReportPanel.setBackground(new java.awt.Color(0, 153, 153));

		jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 0, 0));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("SalesReport");

		javax.swing.GroupLayout SalesReportPanelLayout = new javax.swing.GroupLayout(SalesReportPanel);
		SalesReportPanel.setLayout(SalesReportPanelLayout);
		SalesReportPanelLayout.setHorizontalGroup(SalesReportPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalesReportPanelLayout.createSequentialGroup()
						.addContainerGap(669, Short.MAX_VALUE).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(323, 323, 323)));
		SalesReportPanelLayout
				.setVerticalGroup(
						SalesReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(SalesReportPanelLayout.createSequentialGroup().addGap(115, 115, 115)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(404, Short.MAX_VALUE)));

		layeredPane.add(SalesReportPanel, "card2");

		javax.swing.GroupLayout DashboardPanelLayout = new javax.swing.GroupLayout(DashboardPanel);
		DashboardPanel.setLayout(DashboardPanelLayout);
		DashboardPanelLayout.setHorizontalGroup(DashboardPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(DashboardPanelLayout.createSequentialGroup()
						.addComponent(SlidingMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)
						.addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(DashboardPanelLayout.createSequentialGroup()
										.addComponent(OpenMenu, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(1116, 1116, 1116))
								.addGroup(DashboardPanelLayout.createSequentialGroup().addGap(64, 64, 64)
										.addComponent(Bar, javax.swing.GroupLayout.PREFERRED_SIZE, 1128,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE))
								.addComponent(layeredPane))));
		DashboardPanelLayout.setVerticalGroup(DashboardPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(SlidingMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(DashboardPanelLayout.createSequentialGroup()
						.addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(OpenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(Bar, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(DashboardPanelLayout.createSequentialGroup().addGap(49, 49, 49).addComponent(
										layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(0, 0, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(DashboardPanel,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(DashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	public void switchPanels(JPanel panel) {
		layeredPane.removeAll();
		layeredPane.add(panel);
		layeredPane.repaint();
		layeredPane.revalidate();
	}

	private void formWindowOpened(java.awt.event.WindowEvent evt) {
		switchPanels(SalesReportPanel); // TODO add your handling code here:
	}

	private void OpenMenuMouseReleased(java.awt.event.MouseEvent evt) {

		Thread th = new Thread() {
			public void run() {
				try {
					int width = 26;
					for (int a = 0; a < 10; a++) {
						Thread.sleep(10);
						SlidingMenu.setSize(width, getHeight());
						HideMenu.setSize(width, HideMenu.getHeight());
						width = width + 26;
					}
				} catch (Exception e) {
					String message = "An error has ocurred.";
					JOptionPane.showMessageDialog(rootPane, message);
				}
			}
		};
		th.start();

		// TODO add your handling code here:
	}

	private void HideMenuMouseReleased(java.awt.event.MouseEvent evt) {
		Thread th = new Thread() {
			public void run() {
				try {
					int width = SlidingMenu.getWidth();
					for (int a = 0; a <= 10; a++) {
						Thread.sleep(10);
						SlidingMenu.setSize(width, getHeight());
						width = width - 26;
					}
				} catch (Exception e) {
					String message = "An error has ocurred.";
					JOptionPane.showMessageDialog(rootPane, message);
				}
			}
		};
		th.start(); // TODO add your handling code here:
	}

	private void StockSalesMouseEntered(java.awt.event.MouseEvent evt) {
		StockSales.setBackground(new Color(102, 102, 102)); // TODO add your handling code here:
	}

	private void StockSalesMouseExited(java.awt.event.MouseEvent evt) {
		StockSales.setBackground(new Color(153, 153, 153));
	}

	private void InventoryMouseEntered(java.awt.event.MouseEvent evt) {
		Inventory.setBackground(new Color(102, 102, 102)); // TODO add your handling code here:
	}

	private void InventoryMouseReleased(java.awt.event.MouseEvent evt) {
		switchPanels(InventoryPanel); // TODO add your handling code here:
	}

	private void InventoryMouseExited(java.awt.event.MouseEvent evt) {
		Inventory.setBackground(new Color(153, 153, 153));
	}

	private void StockInMouseEntered(java.awt.event.MouseEvent evt) {
		StockIn.setBackground(new Color(102, 102, 102)); // TODO add your handling code here:
	}

	private void StockInMouseExited(java.awt.event.MouseEvent evt) {
		StockIn.setBackground(new Color(153, 153, 153));
	}

	private void ActivityLogsMouseEntered(java.awt.event.MouseEvent evt) {
		ActivityLogs.setBackground(new Color(102, 102, 102));
	}

	private void ActivityLogsMouseExited(java.awt.event.MouseEvent evt) {
		ActivityLogs.setBackground(new Color(153, 153, 153));
	}

	private void ClientRecordsMouseEntered(java.awt.event.MouseEvent evt) {
		ClientRecords.setBackground(new Color(102, 102, 102));
	}

	private void ClientRecordsMouseExited(java.awt.event.MouseEvent evt) {
		ClientRecords.setBackground(new Color(153, 153, 153));
	}

	private void LogOutMouseEntered(java.awt.event.MouseEvent evt) {
		LogOut.setBackground(new Color(102, 102, 102));
	}

	private void LogOutMouseExited(java.awt.event.MouseEvent evt) {
		LogOut.setBackground(new Color(153, 153, 153));
	}

	private void StockSalesMouseReleased(java.awt.event.MouseEvent evt) {
		switchPanels(SalesReportPanel); // TODO add your handling code here:
	}

	private void StockInMouseReleased(java.awt.event.MouseEvent evt) {
		switchPanels(StockInPanel); // TODO add your handling code here:
	}

	private void ActivityLogsMouseReleased(java.awt.event.MouseEvent evt) {
		switchPanels(ActivityLogsPanel); // TODO add your handling code here:
	}

	private void ClientRecordsMouseReleased(java.awt.event.MouseEvent evt) {
		switchPanels(ClientRecordsPanel); // TODO add your handling code here:
	}

	private void LogOutMouseReleased(java.awt.event.MouseEvent evt) {
		dispose();
		// pantawag sa login page:
		/*
		 * try { LoginPage loginpage = new LoginPage(); } catch ( IOException e1) { //
		 * TODO Auto-generated catch block e1.printStackTrace(); }
		 */
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

				new Dashboard2().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel ActivityLogs;
	private javax.swing.JPanel ActivityLogsPanel;
	private javax.swing.JLabel Bar;
	private javax.swing.JLabel BitMonke;
	private javax.swing.JLabel ClientRecords;
	private javax.swing.JPanel ClientRecordsPanel;
	private javax.swing.JPanel DashboardPanel;
	private javax.swing.JLabel HideMenu;
	private javax.swing.JLabel Inventory;
	private javax.swing.JPanel InventoryPanel;
	private javax.swing.JLabel LogOut;
	private javax.swing.JLabel OpenMenu;
	private javax.swing.JPanel SalesReportPanel;
	private javax.swing.JPanel SlidingMenu;
	private javax.swing.JLabel StockIn;
	private javax.swing.JPanel StockInPanel;
	private javax.swing.JLabel StockSales;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLayeredPane layeredPane;
	// End of variables declaration
}
